# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.9.1

pipelines:
  default:
    - step:
        name: 'Test'
        caches:
          - node
        script:
          - npm install
          - npm run test
  branches:
    master:
      - step:
          name: 'Test&Build'
          caches:
            - node
          script:
            - npm install
            - npm run test
      - step:
          name: 'Publish'
          deployment: production
          script:
            - npm install
            - npm run build
            - pipe: atlassian/npm-publish:0.2.5
              variables:
                NPM_TOKEN: $NPM_TOKEN

